config/routes.rb
SrcPlantx::Engine.routes.draw do
  resources :plants
  
  root :to => 'plants#index'
end

app/models/src_plantx/plant.rb
module SrcPlantx
  class Plant < ActiveRecord::Base
    attr_accessor :active_noupdate

    belongs_to :last_updated_by, :class_name => 'Authentify::User'
    belongs_to :quality_system, :class_name => 'Commonx::MiscDefinition'
    belongs_to :category, :class_name => 'Commonx::MiscDefinition'
   
    email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   
    validates :name, :short_name, :presence => true, :uniqueness => {:case_sensitive => false, :message => I18n.t('Must be unique!')}
    validates :phone, :presence => true
    validates :primary_contact, :primary_cell, :presence => true
    validates :primary_email, :format     => { :with => email_regex, :message => '电邮格式错误！' },
                              :uniqueness => { :case_sensitive => false, :message => '电邮已占用！' },
                              :if => 'primary_email.present?'
    validates :tech_email, :format     => { :with => email_regex, :message => '电邮格式错误！' },
                           :uniqueness => { :case_sensitive => false, :message => '电邮已占用！' },
                           :if => 'tech_email.present?'  
    validates :quality_system_id, :numericality => {:greater_than => 0, :only_integer => true}, :if => 'quality_system_id.present?' 
    validates :supplier_category_id, :numericality => {:greater_than => 0, :only_integer => true}, :if => 'supplier_category_id.present?'
  
    validate :dynamic_validate
    
    def dynamic_validate
      wf = Authentify::AuthentifyUtility.find_config_const('dynamic_validate', 'src_plantx')
      eval(wf) if wf.present?
    end
  end
end

app/controllers/src_plantx/application_controller.rb
module SrcPlantx
  class ApplicationController < ::ApplicationController
    include Authentify::SessionsHelper
    include Authentify::AuthentifyUtility
    include Authentify::UsersHelper
    include Authentify::UserPrivilegeHelper
    include Commonx::CommonxHelper
    
    before_action :require_signin
    before_action :max_pagination 
    before_action :check_access_right 
    before_action :load_session_variable, :only => [:new, :edit]  #for parent_record_id & parent_resource in check_access_right
    after_action :delete_session_variable, :only => [:create, :update]   #for parent_record_id & parent_resource in check_access_right
    before_action :view_in_config?
    before_action :page_params, :only => :index
    
    helper_method :return_users, :return_misc_definitions
    
    protected
  
    def max_pagination
      @max_pagination = find_config_const('pagination')
    end
    
    def view_in_config?
      @view_in_config = Authentify::AuthentifyUtility.load_view_in_config
    end
     
  end
end

app/controllers/src_plantx/plants_controller.rb
require_dependency "src_plantx/application_controller"

module SrcPlantx
  class PlantsController < ApplicationController
    before_action :require_employee
    
    def index
      @title = t('Plants')
      @plants = params[:src_plantx_plants][:model_ar_r].page(params[:page]).per_page(@max_pagination)
      @erb_code = find_config_const('plant_index_view', 'src_plantx')
    end
  
    def new
      @title = t('New Plant')
      @plant = SrcPlantx::Plant.new()
      @erb_code = find_config_const('plant_new_view', 'src_plantx')
    end
  
    def create
      @plant = SrcPlantx::Plant.new(new_params)
      @plant.last_updated_by_id = session[:user_id]
      if @plant.save
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Saved!")
      else
        @erb_code = find_config_const('plant_new_view', 'src_plantx')
        flash[:notice] = t('Data Error. Not Saved!')
        render 'new'
      end
    end
  
    def edit
      @title = t('Update Plant')
      @plant = SrcPlantx::Plant.find_by_id(params[:id])
      @erb_code = find_config_const('plant_edit_view', 'src_plantx')
    end
  
    def update
      @plant = SrcPlantx::Plant.find_by_id(params[:id])
      @plant.last_updated_by_id = session[:user_id]
      if @plant.update_attributes(edit_params)
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Updated!")
      else
        @erb_code = find_config_const('plant_edit_view', 'src_plantx')
        flash[:notice] = t('Data Error. Not Updated!')
        render 'edit'
      end
    end
  
    def show
      @title = t('Show Plant')
      @plant = SrcPlantx::Plant.find_by_id(params[:id])
      @erb_code = find_config_const('plant_show_view', 'src_plantx')
    end
    
    protected
    
    private
    
    def new_params
      params.require(:plant).permit(:active, :address, :customer_service, :employee_num, :equip, :fax, :last_updated_by_id, :main_product, :name, :phone, :primary_cell, 
                    :primary_contact, :production_capacity, :quality_system_id, :revenue, :short_name, :sourced_product, :src_since, :tech_ability, :category_id,
                    :tech_cell, :tech_contact, :primary_email, :tech_email, :web)
    end
    
    def edit_params
      params.require(:plant).permit(:active, :address, :customer_service, :employee_num, :equip, :fax, :last_updated_by_id, :main_product, :name, :phone, :primary_cell, 
                    :primary_contact, :production_capacity, :quality_system_id, :revenue, :short_name, :sourced_product, :src_since, :tech_ability, :category_id,
                    :tech_cell, :tech_contact, :primary_email, :tech_email, :web)
    end
    
  end
end

app/helpers/src_plantx/application_helper.rb
module SrcPlantx
  module ApplicationHelper
  end
end

app/helpers/src_plantx/plants_helper.rb
module SrcPlantx
  module PlantsHelper
  end
end

app/views/src_plantx/plants/_form.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
  
<% else %>
<h1><%=t('Update Plant')%></h1>
<%= simple_form_for @plant do |f| %>    
 
  <%= f.input :name, :label => t('Name') %>  
  <%= f.input :short_name, :label => t('Short Name') %>
  <%= f.input :src_since, :label => t('Since Date'), :as => :string %>
  <%= f.input :primary_contact, :label => t('Primary Contact') %> 
  <%= f.input :primary_cell, :label => t('Cell Phone') %>   
  <%= f.input :primary_email, :label => t('Email') %>  
  <%= f.input :tech_contact, :label => t('Tech Contact') %>  
  <%= f.input :tech_email, :label => t('Email') %> 
  <%= f.input :tech_cell, :label => t('Cell Phone') %>       
  <%= f.input :phone, :label => t('Phone') %> 
  <%= f.input :fax, :label => t('Fax') %>      
  <%= f.input :address, :label => t('Address'), :input_html => { :rows => 2} %>   
  <%= f.input :quality_system_id, :collection =>  Commonx::CommonxHelper.return_misc_definitions('quality_system'), :label => t('Quality System') %>  
  <%= f.input :web, :label => t('Web') %>
  <%= f.input :employee_num, :label => t('Employee#') %> 
  <%= f.input :revenue, :label => t('Revenue'), :hint => '注明单位' %> 
  <%= f.input :main_product, :label => t('Main Product'), :input_html => { :rows => 4} %>   
  <%= f.input :equip, :label => t('Equipment'), :input_html => { :rows => 4} %> 
  <%= f.input :tech_ability, :label => t('Tech Ability'), :input_html => { :rows => 4} %>  
  <%= f.input :production_capacity, :label => t('Production Capacity'), :input_html => { :rows => 4} %>      
  <%= f.input :customer_service, :label => t('Customer Service'), :input_html => { :rows => 4} %>         
  <%= f.input :sourced_product, :label => t('Srouced Product'), :hint => '给本公司制造过的设备', :input_html => { :rows => 4} %>      
  <% if readonly?(@plant, 'active')%>
     <%= f.input :active_noupdate, :label => t('Active'), :readonly => true, :required => false, :input_html => {:value => @plant.active} %>
  <% else %>
     <%= f.input :active, :label => t('Active'), :collection => [[t('Yes'), true], [t('No'), false]]%>
  <% end %>               
  
  <%= link_to t('Back'), SUBURI + "/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>  
<% end %>  

<% end %>

app/views/src_plantx/plants/_form_list.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
<% else %>
<h1><%=t('Plants')%></h1>
<div class="pagination"><%= will_paginate models %></div>
<table class="table table-striped">
  <tr>
    <th>#</th>
    <th><%=t('Short Name')%></th>
    <th><%=t('Since Date')%></th>
    <th><%=t('Primary Contact')%></th>
    <th><%=t('Primary Cell')%></th>
    <th><%=t('Phone')%></th>
    <th><%=t('Fax')%></th>
    <th><%=t('Active')%></th>
    <th><%=t('Main Product')%></th>
    <th><%=t('Sourced Product')%></th>
    <th></th>
 
  </tr>

<% models.each do |r| %>
  <tr>
  	<td><%= link_to r.id.to_s, SUBURI + "/view_handler?index=1&url=#{plant_path(r)}"  %></td>
    <td><%= r.short_name %></td>
    <td><%= r.src_since.strftime("%Y/%m/%d") unless r.src_since.nil? %></td>
    <td><%= prt(r, :primary_contact) %></td>
    <td><%= prt(r, :primary_cell) %></td>
    <td><%= prt(r, :phone) %></td>
    <td><%= prt(r, :fax) %></td>
    <td><%= r.active ? t('Yes') : t('No') %></td>
    <td><%= r.main_product %></td>
    <td><%= r.sourced_product %></td> 
    <td><%= link_to t('Edit'), SUBURI + "/view_handler?index=1&url=#{edit_plant_path(r)}", :class => BUTTONS_CLS['action'] if has_action_right?('update', params[:controller], r) %></td>

  </tr>
<% end %>
</table>
<table class="table table-striped">
  <%= link_to t('Back'), SUBURI + "/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  &nbsp;<%= link_to t('New Plant'), SUBURI + "/view_handler?index=1&url=#{new_plant_path}", :class => BUTTONS_CLS['action'] if has_action_right?('create', params[:controller]) %>  
</table>

<% end %>

app/views/src_plantx/plants/_form_new.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
  
<% else %>
<h1><%=t('New Plant')%></h1>
<%= simple_form_for @plant do |f| %>    
 
  <%= f.input :name, :label => t('Name') %>  
  <%= f.input :short_name, :label => t('Short Name'), :hint => '4-8字' %>
  <%= f.input :src_since, :label => t('Since Date'), :hint => '开始外协日期', :as => :string %>
  <%= f.input :primary_contact, :label => t('Primary Contact') %> 
  <%= f.input :primary_cell, :label => t('Cell Phone') %>   
  <%= f.input :primary_email, :label => t('Email') %>  
  <%= f.input :tech_contact, :label => t('Tech Contact') %>  
  <%= f.input :tech_email, :label => t('Email') %> 
  <%= f.input :tech_cell, :label => t('Cell Phone') %>       
  <%= f.input :phone, :label => t('Phone') %> 
  <%= f.input :fax, :label => t('Fax') %>      
  <%= f.input :address, :label => t('Address'), :input_html => { :rows => 2} %>   
  <%= f.input :quality_system_id, :collection =>  Commonx::CommonxHelper.return_misc_definitions('quality_system'), :label => t('Quality System'), :include_blank => true %>  
  <%= f.input :web, :label => t('Web') %>
  <%= f.input :employee_num, :label => t('Employee#') %> 
  <%= f.input :revenue, :label => t('Revenue'), :hint => '注明单位' %> 
  <%= f.input :main_product, :label => t('Main Product'), :input_html => { :rows => 4} %>   
  <%= f.input :equip, :label => t('Equipment'), :input_html => { :rows => 4} %> 
  <%= f.input :tech_ability, :label => t('Tech Ability'), :input_html => { :rows => 4} %>  
  <%= f.input :production_capacity, :label => t('Production Capacity'), :input_html => { :rows => 4} %>      
  <%= f.input :customer_service, :label => t('Customer Service'), :input_html => { :rows => 4} %>         
  <%= f.input :sourced_product, :label => t('Srouced Product'), :hint => '给本公司制造过的设备', :input_html => { :rows => 4} %>              
  
  <%= link_to t('Back'), SUBURI + "/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>  
<% end %>  

<% end %>

app/views/src_plantx/plants/create.html.erb
<h1>SrcPlants#create</h1>
<p>Find me in app/views/src_plants/create.html.erb</p>

app/views/src_plantx/plants/edit.html.erb
<%= render 'form' %>

app/views/src_plantx/plants/index.html.erb
	
	<%= render partial: 'form_list', locals: {models: @plants} %>
 

app/views/src_plantx/plants/new.html.erb
<%= render 'form_new' %>

app/views/src_plantx/plants/show.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
<% else %>


<h1><%=t('Plant Info')%></h1>

<p>
  <b><%=t('Name') %></b>
  <%= @plant.name %>
</p>
<p>
  <b><%=t('Short Name') %></b>
  <%= @plant.short_name %>
</p>
<p>
  <b><%=t('Sourcing Since') %></b>
  <%= @plant.src_since.strftime("%Y/%m/%d") unless @plant.src_since.nil? %>
</p>
<p>
  <b><%=t('Primary Contact') %></b>
  <%= @plant.primary_contact %>
</p>
<p>
  <b><%=t('Cell Phone') %></b>
  <%= @plant.primary_cell %>
</p>
<p>
  <b><%=t('Primary Email') %></b>
  <%= @plant.primary_email %>
</p>
<p>
  <b><%=t('Tech Contact') %></b>
  <%= @plant.tech_contact %>
</p>
<p>
  <b><%=t('Cell Phone') %></b>
  <%= @plant.tech_cell %>
</p>
<p>
  <b><%=t('Tech Email') %></b>
  <%= @plant.primary_email %>
</p>
<p>
  <b><%=t('Phone') %></b>
  <%= @plant.phone %>
</p>
<p>
  <b><%=t('Fax') %></b>
  <%= @plant.fax %>
</p>
<p>
  <b><%=t('Address') %></b>
  <%= @plant.address %>
</p>
<p>
  <b><%=t('Web') %></b>
  <%= @plant.web %>
</p>
<p>
  <b><%=t('Main Product') %></b>
  <%= @plant.main_product %>
</p>
<p>
  <b><%=t('Quality System') %></b>
  <%= @plant.quality_system.name if @plant.quality_system_id.present? %>
</p>
<p>
  <b><%=t('Revenue')%></b>
  <%= @plant.revenue %>
</p>
<p>
  <b><%=t('Employee#')%></b>
  <%= @plant.employee_num %>
</p>
<p>
  <b><%=t('Sourced Product')%></b>
  <%= @plant.sourced_product %>
</p>
<p>
  <b><%=t('Equipment')%></b>
  <%= @plant.equip %>
</p>
<p>
  <b><%=t('Tech Ability')%></b>
  <%= @plant.tech_ability %>
</p>
<p>
  <b><%=t('Customer Service')%></b>
  <%= @plant.customer_service %>
</p>
<p>
  <b><%=t('Production Capacity')%></b>
  <%= @plant.production_capacity %>
</p>
<p>
  <b><%= t('Active') %></b>
  <%= @plant.active ? t('Yes') : t('No') %>
</p>
<p>
  <b><%= t('Last Updated By') %></b>
  <%= @plant.last_updated_by.name %>
</p>
</ul>
</p>
<table class="table table-striped">
  <tr>
    <th>
    <%= link_to t('Back'), SUBURI + "/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
    </th>
  </tr>
</table>



<% end %>

app/views/src_plantx/plants/update.html.erb
<h1>SrcPlants#update</h1>
<p>Find me in app/views/src_plants/update.html.erb</p>